[project]
name = "hn-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.14.2",
    "requests>=2.32.4",
    "rich>=14.0.0",
]

[project.scripts]
hnd = "main:main"
